"""Plot the DAC sweep generated by example-01."""

from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path

import matplotlib.pyplot as plt


DATA_ROW = re.compile(
    r"^\s*(?P<attenuation>[-+]?\d+(?:\.\d+)?)\s+"
    r"(?P<unit>dB|%)\s+\|\s+"
    r"(?P<dac_code>\d+)\s*$"
)
PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_EXECUTABLE = PROJECT_ROOT / "build" / "example-01.exe"


def parse_output(output: str) -> tuple[list[float], list[int], str]:
    """Extract attenuation and DAC code values from example output."""
    attenuation_values: list[float] = []
    dac_codes: list[int] = []
    unit: str | None = None

    for line in output.splitlines():
        match = DATA_ROW.match(line)
        if match is None:
            continue
        current_unit = match.group("unit")
        if unit is None:
            unit = current_unit
        elif current_unit != unit:
            raise ValueError("Example output contains mixed attenuation units.")
        attenuation_values.append(float(match.group("attenuation")))
        dac_codes.append(int(match.group("dac_code")))

    if not attenuation_values:
        raise ValueError("No DAC sweep rows were found in the example output.")

    return attenuation_values, dac_codes, unit or "dB"


def read_example_output(
    executable: Path, input_file: Path | None, percent_sweep: bool
) -> str:
    """Run the example or read previously captured output."""
    if input_file is not None:
        return input_file.read_text(encoding="utf-8")

    if not executable.is_file():
        raise FileNotFoundError(
            f"Example executable not found: {executable}. "
            "Build it first or pass --input with captured output."
        )

    command = [str(executable)]
    if percent_sweep:
        command.append("--percent")

    result = subprocess.run(
        command,
        cwd=PROJECT_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout


def plot_sweep(
    attenuation_values: list[float],
    dac_codes: list[int],
    unit: str,
    output_file: Path | None,
) -> None:
    """Plot the DAC code as a function of target attenuation."""
    fig, axis = plt.subplots(figsize=(9, 5.5))
    axis.plot(dac_codes, attenuation_values,
              marker="o", markersize=3, linewidth=1.5)
    axis.set_title("VOA DAC Sweep")
    axis.set_xlabel("DAC code")
    axis.set_ylabel(f"Target attenuation ({unit})")
    axis.grid(True, alpha=0.3)
    fig.tight_layout()

    if output_file is not None:
        fig.savefig(output_file, dpi=150)
        print(f"Saved plot to {output_file}")
    else:
        plt.show()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--executable",
        type=Path,
        default=DEFAULT_EXECUTABLE,
        help=f"Path to example-01 (default: {DEFAULT_EXECUTABLE})",
    )
    parser.add_argument(
        "--input",
        type=Path,
        help="Read captured example output instead of running the executable.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Save the plot to an image instead of opening a window.",
    )
    parser.add_argument(
        "--percent",
        action="store_true",
        help="Run and plot the percent attenuation sweep.",
    )
    args = parser.parse_args()

    output = read_example_output(args.executable, args.input, args.percent)
    attenuation_values, dac_codes, unit = parse_output(output)
    plot_sweep(attenuation_values, dac_codes, unit, args.output)


if __name__ == "__main__":
    main()
